map $http_accept $webp_suffix {
  default "";
  "~*webp" ".webp";
}
map $http_accept $avif_suffix {
  default "";
  "~*avif" ".avif";
}
map $http_user_agent $bad_ua {
  default 0;
  include /etc/nginx/bots/bad-user-agents.conf;
}
map $remote_addr $bad_ip {
  default 0;
  include /etc/nginx/bots/bad-ip-list.conf;
  include /etc/nginx/bots/fake-googlebots.conf;
}
map $http_referer $bad_referrer {
  default 0;
  include /etc/nginx/bots/bad-referrers.conf;
}

map $http_user_agent $block_ai {
    default 0;
    ~*GPTBot 1;
    ~*ChatGPT-User 1;
    ~*CCBot 1;
    ~*ClaudeBot 1;
    ~*Claude-Web 1;
    ~*anthropic-ai 1;
    ~*PerplexityBot 1;
    ~*YouBot 1;
    ~*Bytespider 1;
    ~*Amazonbot 1;
    ~*Google-Extended 1;
}